apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: madfam-site
  project: madfam-site
spec:
  runtime:
    port: 3000
  domains:
    - name: madfam.io
    - name: www.madfam.io
    - name: docs.madfam.io
  network:
    services:
      - name: madfam-web
        port: 3000
        ingress: [cloudflare-tunnel]
        egress: [dns, https]
      - name: madfam-cms
        port: 3000
        ingress: [cloudflare-tunnel]
        egress: [dns, https, postgres]
