apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madfam-site

resources:
- namespace.yaml
- madfam-web-deployment.yaml
- madfam-web-service.yaml
- madfam-cms-deployment.yaml
- madfam-cms-service.yaml
- network-policies.yaml
- resource-quota.yaml
- madfam-web-hpa.yaml
# secrets-template.yaml excluded — managed manually via kubectl
# Live secret has argocd.argoproj.io/sync-options: Prune=false annotation

labels:
- pairs:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:45a31fc617f1ec26296ce54a4a18b24c2557717eefb0e122fb2f9e251c41c4a6
  name: ghcr.io/madfam-org/madfam-site/cms
  newName: ghcr.io/madfam-org/madfam-site/cms
- digest: sha256:2764a947494d796a969910b42b6b4127c63725971cf4e9fcb72b064f3fe3fdf3
  name: ghcr.io/madfam-org/madfam-site/web
  newName: ghcr.io/madfam-org/madfam-site/web
