apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madfam-site

resources:
- namespace.yaml
- madfam-web-deployment.yaml
- madfam-web-service.yaml
- madfam-cms-deployment.yaml
- madfam-cms-service.yaml
- network-policies.yaml
- resource-quota.yaml
# secrets-template.yaml excluded — managed manually via kubectl
# Live secret has argocd.argoproj.io/sync-options: Prune=false annotation

labels:
- pairs:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard

images:
- digest: sha256:95f1dc3769f01f3560497b47312fb082e9ea9531fcaf3cc51fa05bc6d71d58a9
  name: ghcr.io/madfam-org/madfam-site/cms
  newName: ghcr.io/madfam-org/madfam-site/cms
- digest: sha256:43b8334dfb657c59c72a4e8784da3d7a1df7ff7285fbcc66f04e5520491ec071
  name: ghcr.io/madfam-org/madfam-site/web
  newName: ghcr.io/madfam-org/madfam-site/web
