---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: madfam-site-quota
  labels:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1Gi
    limits.cpu: 1500m
    limits.memory: 2Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: madfam-site-limits
  labels:
    app.kubernetes.io/part-of: madfam-platform
    enclii.dev/managed-by: switchyard
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
